# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lname',
            new_name='last_lname',
        ),
    ]
